spring:
  redis:
    host: 192.168.1.101
    # Redis服务器连接端口
    port: 6060
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最小空闲连接
        max-idle: 10
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 100000
    # 连接超时时间（毫秒）
    timeout: 5000
    #默认是索引为0的数据库
    database: 0
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
server:
  port: 8888
